### ISSUE TITLE
Items Moving into off hand

### ISSUE THREAD

**Issue by benbenlaw** [benbenlaw/skyopolis-5#13] opened 2022-06-27 14:41 UTC
Items randomly seen to go into off hand any information is helpful

**Comment by CaptAlex1092** [comment] 2022-07-01 22:06
It's from the mod that replaces blocks/items in your hotbar when you finish a stack of blocks/break an item.
Easy way to reproduce:
1)Have an item in your main hand.
2)Throw another item from your inventory either via the drop key or drag and dropping outside the inventory window(You need to have at least 2 of that item before you drop it)
When you throw an item from your inventory for some reason the mod thinks you finished a stack and moves a new stack of that item into your main hand.If the main hand is occupied by something else,it moves the new stack into the offhand.If both hands are occupied nothing happens.
Edit:The mod is Stack Refill by Serilum

**Comment by ricksouth** [comment] 2022-09-20 20:39
This has been fixed in version 3.0 of Stack Refill. Appreciate you giving the mod a try!

**Comment by Gurkysword12** [comment] 2023-02-17 18:42
Fixed in Dev(due to mod update)

**Closed as completed by Gurkysword12** 2023-02-17 18:42 UTC
Labels: bug, awaiting support
