### ISSUE TITLE
Essence Converter Quest wrong detection

### ISSUE THREAD

**Issue by Pinguin34** [benbenlaw/skyopolis-5#14] opened 2022-06-30 09:09 UTC
**Modpack version : B4.1**

I craft the Lignthing Infuser and this item has completed the Essence converter quest whitout craft the Essence Converter item.

![quest](https://user-images.githubusercontent.com/82638188/176638099-b66c5807-8bf7-4d1d-bc32-9e05d65a4f1d.png)
![lightning](https://user-images.githubusercontent.com/82638188/176638298-e1f720d9-0948-410f-8322-011eaa8d2f37.png)

**Both item as the same ID : custommachinery:custom_machine_item**

![Essence ID](https://user-images.githubusercontent.com/82638188/176638630-76d98e6d-28a8-4775-b8ee-92164169c49f.png)
![Lightning ID](https://user-images.githubusercontent.com/82638188/176638921-33967efa-8348-49bb-9859-6383dd196efa.png)

**Comment by benbenlaw** [comment] 2022-06-30 09:32
yeah i know how to fix but (using it for the singulairties later on in the quest lines) but the issue is you can view the recipes from inside the quests

**Comment by benbenlaw** [comment] 2022-06-30 09:32
i keep asking in there discord and not getting any responces so i left as is at the moment

**Comment by Gurkysword12** [comment] 2023-02-17 18:39
Fixed in Dev

**Closed as completed** 2023-02-17 18:40 UTC
Labels: bug, awaiting support
